{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pickle\n",
    "from flask import Flask, jsonify, request\n",
    "import pandas as pd\n",
    "import joblib\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "file_name = 'best_model.pkl'\n",
    "port = 5000"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app '__main__'\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[31m\u001b[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\u001b[0m\n",
      " * Running on all addresses (0.0.0.0)\n",
      " * Running on http://127.0.0.1:5000\n",
      " * Running on http://192.168.0.33:5000\n",
      "\u001b[33mPress CTRL+C to quit\u001b[0m\n",
      "/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator OneHotEncoder from version 1.2.1 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:\n",
      "https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations\n",
      "  warnings.warn(\n",
      "[2023-08-27 23:09:10,413] ERROR in app: Exception on /predict [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/var/folders/sf/xg0v4rmj5lgd3p3m2yh1kth40000gq/T/ipykernel_16586/768882043.py\", line 9, in do_prediction\n",
      "    model = unpickler.load()\n",
      "AttributeError: Can't get attribute 'simple_imputer' on <module '__main__'>\n",
      "127.0.0.1 - - [27/Aug/2023 23:09:10] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n",
      "[2023-08-27 23:10:24,718] ERROR in app: Exception on /predict [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/var/folders/sf/xg0v4rmj5lgd3p3m2yh1kth40000gq/T/ipykernel_16586/768882043.py\", line 9, in do_prediction\n",
      "    model = unpickler.load()\n",
      "AttributeError: Can't get attribute 'simple_imputer' on <module '__main__'>\n",
      "127.0.0.1 - - [27/Aug/2023 23:10:24] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n",
      "[2023-08-27 23:10:26,646] ERROR in app: Exception on /predict [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/var/folders/sf/xg0v4rmj5lgd3p3m2yh1kth40000gq/T/ipykernel_16586/768882043.py\", line 9, in do_prediction\n",
      "    model = unpickler.load()\n",
      "AttributeError: Can't get attribute 'simple_imputer' on <module '__main__'>\n",
      "127.0.0.1 - - [27/Aug/2023 23:10:26] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n",
      "[2023-08-27 23:11:42,784] ERROR in app: Exception on /predict [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/var/folders/sf/xg0v4rmj5lgd3p3m2yh1kth40000gq/T/ipykernel_16586/768882043.py\", line 9, in do_prediction\n",
      "    model = unpickler.load()\n",
      "AttributeError: Can't get attribute 'simple_imputer' on <module '__main__'>\n",
      "127.0.0.1 - - [27/Aug/2023 23:11:42] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n",
      "[2023-08-27 23:20:16,670] ERROR in app: Exception on /predict [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/var/folders/sf/xg0v4rmj5lgd3p3m2yh1kth40000gq/T/ipykernel_16586/768882043.py\", line 9, in do_prediction\n",
      "    model = unpickler.load()\n",
      "AttributeError: Can't get attribute 'simple_imputer' on <module '__main__'>\n",
      "127.0.0.1 - - [27/Aug/2023 23:20:16] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n",
      "[2023-08-27 23:20:19,949] ERROR in app: Exception on /predict [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/anaconda3/envs/mlpipeline/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/var/folders/sf/xg0v4rmj5lgd3p3m2yh1kth40000gq/T/ipykernel_16586/768882043.py\", line 9, in do_prediction\n",
      "    model = unpickler.load()\n",
      "AttributeError: Can't get attribute 'simple_imputer' on <module '__main__'>\n",
      "127.0.0.1 - - [27/Aug/2023 23:20:19] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    }
   ],
   "source": [
    "#importing necessary libraries\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "@app.route(\"/predict\", methods=['POST'])\n",
    "def do_prediction():\n",
    "    #loading saved model here in this python file\n",
    "    unpickler = pickle.Unpickler(open(file_name, 'rb'))\n",
    "    model = unpickler.load()\n",
    "\n",
    "    #creating data frame of JSON data\n",
    "    json = request.get_json()\n",
    "    train = pd.DataFrame(json, index=[0])\n",
    "    # predict\n",
    "    y_predict = model.predict(train)\n",
    "    res= {\"Predicted note of rmse\" : y_predict[0]}\n",
    "    return jsonify(res)\n",
    "    # Save response to a text file\n",
    "    \n",
    "   \n",
    "if __name__ == \"__main__\":\n",
    "    app.run(host='0.0.0.0', port=port)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "from flask import Flask, jsonify, request\n",
    "import pandas as pd\n",
    "import pickle\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "# Define the custom function in the global scope\n",
    "def simple_imputer(X):\n",
    "    return X.fillna(X.median())\n",
    "def scale(X):\n",
    "    std_dev = X.std()\n",
    "    if (std_dev == 0).all():\n",
    "        return X - X.mean()\n",
    "    return (X - X.mean()) / std_dev\n",
    "\n",
    "# Load the model after the function definition\n",
    "file_name = 'best_model.pkl'\n",
    "with open(file_name, 'rb') as f:\n",
    "    model = pickle.load(f)\n",
    "\n",
    "@app.route(\"/predict\", methods=['POST'])\n",
    "def do_prediction():\n",
    "    try:\n",
    "        # Creating DataFrame from JSON data\n",
    "        data = request.get_json()\n",
    "        df = pd.DataFrame(data, index=[0])\n",
    "\n",
    "        # Predict\n",
    "        y_predict = model.predict(df)\n",
    "        res = {\"Predicted note of rmse\": y_predict[0]}\n",
    "        return jsonify(res)\n",
    "    except Exception as e:\n",
    "        return jsonify({'error': str(e)})\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    port = 5000\n",
    "    app.run(host='0.0.0.0', port=port)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "\n",
    "url = 'http://localhost:5000/predict'\n",
    "dict_x = train.iloc[0].to_dict()\n",
    "r = requests.post(url, json=dict_x)\n",
    "print(r.json())\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10.0 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "7e1998ff7f8aa20ada591c520b972326324e5ea05489af9e422744c7c09f6dad"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
